### There are various techniques for transforming data into a machine-readable format.

### Traditional approach:

- Each transformation technique is defined separately, and then we fit each technique to the data, leading to potentially lengthy code.

### Scikit-learn’s column transformer library :

- It allows us to specify different transformation techniques along with their parameters in a single step.

- This way, the data can be transformed all at once, providing a more concise and organized solution.

- Scikit-Learn’s Column Transformer is a powerful tool for applying different transformations to different columns of a dataset.

- It allows you to define a set of transformers and specify which columns each transformer should be applied to.

- This is particularly useful when dealing with datasets that have heterogeneous data types or when you want to apply different preprocessing steps to different subsets of features.

#### Steps 

1. Import necessary libraries:

   
   `from sklearn.compose import ColumnTransformer
    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import StandardScaler, OneHotEncoder`

3. Specify the features(categorical and numerical):

   `# Specify Features and Transformers

   
    scaling_features = ['scaling_column1', 'scaling_column2']

   
    imputer_features = ['imputer_column1', 'imputer_column2']
    categorical_features = ['categorical_column1', 'categorical_column2']`

5. Specify Transformer:

    Combine Transformers using ColumnTransformer-

    `preprocessor = ColumnTransformer(
    transformers=[
            ('SI', SimpleImputer(), imputer_features),
            ('SS', StandardScaler(), scaling_features),
            ('OHE', OneHotEncoder(sparse=False), categorical_features], 
            remainder='passthrough'
    )`

     In the transformer, 
     SI is a given name for that transformation
     SimpleImputer is a sklearn library for transformation
     imputer_features are the columns/features

   

In [2]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df=pd.read_csv('/kaggle/input/datasets/shashikalarajesh11/covid-toy-data/covid_toy.csv')

In [5]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


#### We have following columns :

1. Categorical Columns ( gender,cough,city )
2. Numerical Columns ( age, fever )

#### for categoical columns we will APPLY :

- OneHotEncoding for (gender, city)
- Ordinal Encoding for (cough)
- Label Encoding for (has_covid)
- simple imputer for (fever)

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.3)

### Aam Zindagi

### 1. SimpleImputer() -> It replaces all the null values to mean values of fever column

In [12]:
# adding simple imputer to fever col
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever=si.fit_transform(X_test[['fever']])

X_train_fever

array([[ 99.   ],
       [102.   ],
       [101.   ],
       [103.   ],
       [103.   ],
       [100.875],
       [ 99.   ],
       [100.875],
       [104.   ],
       [102.   ],
       [ 98.   ],
       [100.875],
       [102.   ],
       [ 99.   ],
       [ 98.   ],
       [100.   ],
       [100.   ],
       [102.   ],
       [102.   ],
       [104.   ],
       [103.   ],
       [104.   ],
       [104.   ],
       [104.   ],
       [104.   ],
       [ 98.   ],
       [101.   ],
       [ 99.   ],
       [104.   ],
       [ 99.   ],
       [ 98.   ],
       [101.   ],
       [101.   ],
       [100.875],
       [ 98.   ],
       [100.   ],
       [100.   ],
       [104.   ],
       [100.   ],
       [104.   ],
       [104.   ],
       [103.   ],
       [ 99.   ],
       [ 98.   ],
       [101.   ],
       [ 99.   ],
       [ 98.   ],
       [101.   ],
       [ 98.   ],
       [ 98.   ],
       [ 99.   ],
       [ 98.   ],
       [100.875],
       [ 98.   ],
       [102.   ],
       [10

In [13]:
X_train_fever.shape

(70, 1)

### 2. Odinal Encoding on cough column

In [14]:
# OrdinalEncoding
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough=oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(70, 1)

### 3.OneHotEncoding on city and gender column

convert to array because without this it acts as object so we'll make it array

In [22]:
ohe=OneHotEncoder(drop='first')
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']]).toarray()

# also the test data
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']]).toarray()

In [23]:
# Extracting age

X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data 
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(70, 1)

In [24]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

# also the test data

X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[ 49.   ,  99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [  5.   , 102.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 64.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 70.   , 103.   ,   1.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 73.   , 103.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 82.   , 100.875,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 72.   ,  99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 84.   , 100.875,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 25.   , 104.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 64.   , 102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 31.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 42.   , 100.875,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 82.   , 102.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 65.   ,  99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   

### Mentos Zindagi 
        -By CampusX

In [25]:
from sklearn.compose import ColumnTransformer

ColumnTransformer has two arguments :

- Columns which has to be transformed
- Columns which is remainder (has two options : drop and passthrough)
- drop is used for dropping the column.
- passthrough is used for passing the columns as it is to transformer 

In [37]:
transformer=ColumnTransformer(transformers=[
 ('tnf1',SimpleImputer(),['fever']),
 ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
 ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
    
],remainder='passthrough')

In [38]:
transformer.fit_transform(X_train)

array([[ 99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  49.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,   5.   ],
       [101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  64.   ],
       [103.   ,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  70.   ],
       [103.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  73.   ],
       [100.875,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  82.   ],
       [ 99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  72.   ],
       [100.875,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  84.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  25.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  64.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  31.   ],
       [100.875,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  42.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  82.   ],
       [ 99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  6

In [40]:
transformer.transform(X_train).shape

(70, 7)

In [39]:
transformer.transform(X_test).shape

(30, 7)